### ISSUE TITLE
Browser display/reloading from gulp is broken

### ISSUE THREAD

**Issue by mxsasha** [writethedocs/www#1042]
Gulp currently throws the following error:

```
assert.js:341
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/sasha/dev/writethedocs-www/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/sasha/dev/writethedocs-www/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/sasha/dev/writethedocs-www/gulpfile.js:38:6)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at execute (/Users/sasha/dev/writethedocs-www/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
```

This error can be avoided by removing all the highlighted tasks here: https://github.com/writethedocs/www/blob/master/gulpfile.js#L30-L48
Presumably, something is broken about the configuration of these tasks. Discovered during #1010, but may be kept out of scope for that.

**Comment by plaindocs** [comment]
Fixed by #1066
